package persistence.entities;
// Generated 12 avr. 2021 à 11:47:54 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "HOTEL", schema = "AGENCEDB")
public class Hotel implements java.io.Serializable {

	private BigDecimal idhotel;
	private String nomHotel;
	private String nbreetoile;
	private String adresseHotel;
	private BigDecimal nbrechambre;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Hotel() {
	}

	public Hotel(BigDecimal idhotel) {
		this.idhotel = idhotel;
	}

	public Hotel(BigDecimal idhotel, String nomHotel, String nbreetoile, String adresseHotel, BigDecimal nbrechambre,
			Set<Reservation> reservations) {
		this.idhotel = idhotel;
		this.nomHotel = nomHotel;
		this.nbreetoile = nbreetoile;
		this.adresseHotel = adresseHotel;
		this.nbrechambre = nbrechambre;
		this.reservations = reservations;
	}

	@Id

	@Column(name = "IDHOTEL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdhotel() {
		return this.idhotel;
	}

	public void setIdhotel(BigDecimal idhotel) {
		this.idhotel = idhotel;
	}

	@Column(name = "NOM_HOTEL", length = 20)
	public String getNomHotel() {
		return this.nomHotel;
	}

	public void setNomHotel(String nomHotel) {
		this.nomHotel = nomHotel;
	}

	@Column(name = "NBREETOILE", length = 20)
	public String getNbreetoile() {
		return this.nbreetoile;
	}

	public void setNbreetoile(String nbreetoile) {
		this.nbreetoile = nbreetoile;
	}

	@Column(name = "ADRESSE_HOTEL", length = 20)
	public String getAdresseHotel() {
		return this.adresseHotel;
	}

	public void setAdresseHotel(String adresseHotel) {
		this.adresseHotel = adresseHotel;
	}

	@Column(name = "NBRECHAMBRE", precision = 22, scale = 0)
	public BigDecimal getNbrechambre() {
		return this.nbrechambre;
	}

	public void setNbrechambre(BigDecimal nbrechambre) {
		this.nbrechambre = nbrechambre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
