package persistence.entities;
// Generated 12 avr. 2021 à 11:47:54 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "RESERVATION", schema = "AGENCEDB")
public class Reservation implements java.io.Serializable {

	private BigDecimal idreservation;
	private Hotel hotel=new Hotel();
	private Client client=new Client();
	private Date dateReservation;
	private Date dateDepart;
	private Date dateArrivee;
	private BigDecimal nbrenuites;
	private BigDecimal nbPersonnes;
	private String typePension;

	public Reservation() {
	}

	public Reservation(BigDecimal idreservation) {
		this.idreservation = idreservation;
	}

	public Reservation(BigDecimal idreservation, Hotel hotel, Client client, Date dateReservation, Date dateDepart,
			Date dateArrivee, BigDecimal nbrenuites, BigDecimal nbPersonnes, String typePension) {
		this.idreservation = idreservation;
		this.hotel = hotel;
		this.client = client;
		this.dateReservation = dateReservation;
		this.dateDepart = dateDepart;
		this.dateArrivee = dateArrivee;
		this.nbrenuites = nbrenuites;
		this.nbPersonnes = nbPersonnes;
		this.typePension = typePension;
	}

	@Id
	@Column(name = "IDRESERVATION", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "RESERVATION_SEQ", sequenceName = "RESERVATION_SEQ")
	public BigDecimal getIdreservation() {
		return this.idreservation;
	}

	public void setIdreservation(BigDecimal idreservation) {
		this.idreservation = idreservation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDHOTEL")
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
	@JoinColumn(name = "IDCLIENT")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_RESERVATION", length = 7)
	public Date getDateReservation() {
		return this.dateReservation;
	}

	public void setDateReservation(Date dateReservation) {
		this.dateReservation = dateReservation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEPART", length = 7)
	public Date getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(Date dateDepart) {
		this.dateDepart = dateDepart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ARRIVEE", length = 7)
	public Date getDateArrivee() {
		return this.dateArrivee;
	}

	public void setDateArrivee(Date dateArrivee) {
		this.dateArrivee = dateArrivee;
	}

	@Column(name = "NBRENUITES", precision = 22, scale = 0)
	public BigDecimal getNbrenuites() {
		return this.nbrenuites;
	}

	public void setNbrenuites(BigDecimal nbrenuites) {
		this.nbrenuites = nbrenuites;
	}

	@Column(name = "NB_PERSONNES", precision = 22, scale = 0)
	public BigDecimal getNbPersonnes() {
		return this.nbPersonnes;
	}

	public void setNbPersonnes(BigDecimal nbPersonnes) {
		this.nbPersonnes = nbPersonnes;
	}

	@Column(name = "TYPE_PENSION", length = 20)
	public String getTypePension() {
		return this.typePension;
	}

	public void setTypePension(String typePension) {
		this.typePension = typePension;
	}

}
